### ISSUE TITLE
pub get- quiver _hashcode

### ISSUE THREAD

**Issue by scorpion047** [glynskyi/zefyrka#11]
Because quill_delta >=1.0.0-dev.3.0 depends on quiver_hashcode ^2.0.0 and every version of zefyrka depends on quiver_hashcode ^3.0.0+1, quill_delta >=1.0.0-dev.3.0 is incompatible with zefyrka.
So, because fashow depends on both quill_delta ^2.0.0 and zefyrka ^1.0.1, version solving failed.

**Comment by glynskyi** [comment]
fixed in [zefyrka: ^1.0.5](https://pub.dev/packages/zefyrka/changelog#105)
