### ISSUE TITLE
ZefyrimageDelegate removed? Is there a way to handle picked images and ulpoad to firebase?

### ISSUE THREAD

**Issue by marc-walton** [glynskyi/zefyrka#12]

**Comment by stanonyime** [comment]
Same here

**Comment by glynskyi** [comment]
Now Zefyrka editor is not responsible to manage images. You can use `ZefyrEmbedBuilder` to  build and embed objects (like image, video, etc). Please see [an example](https://github.com/glynskyi/zefyrka/issues/19#issuecomment-888968308)
