### ISSUE TITLE
Notus to HTML converter

### ISSUE THREAD

**Issue by dumilonz** [glynskyi/zefyrka#17]
Is there a project similar to https://github.com/JacobWrenn/notustohtml/blob/master/lib/notustohtml.dart that will allow for delta to HTML conversion for this new Delta object created in Zefyrka?

**Comment by featzima** [comment]
I converted the `quill_delta` package was used in the original `zefyr` package to the null safety and republished it as `quill_format` package. So you just need to change imports from
```
import 'package:quill_delta/quill_delta.dart';
```
to 
```
import 'package:quill_format/quill_format.dart';
```
and everything should work as previously.

**Comment by ksilz** [comment]
I'm sorry but I don't see anything that looks like the [NotusHtmlCodec](https://github.com/JacobWrenn/notustohtml/blob/master/lib/notustohtml.dart) in your libraries. Can you please point the way?
