### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by LoveCTTS** [glynskyi/zefyrka#22]
I used example code for test.

but result is 

![frontend](https://user-images.githubusercontent.com/42003685/127846860-d200555d-7644-4de7-9079-692b29201588.PNG)

i just copy and paste example code in my project

why???

![code1](https://user-images.githubusercontent.com/42003685/127846940-e2d05e02-9f95-478a-a3e2-ab48ce8c72d0.PNG)

![code2](https://user-images.githubusercontent.com/42003685/127846948-2bb69ad5-3f22-44de-a6fb-b4b37aa8c187.PNG)

**Comment by glynskyi** [comment]
@LoveCTTS Thank you for your feedback! The issue was in a missed focus node. Now Zeryrka doesn't require a focus node. Please update to [1.0.10](https://pub.dev/packages/zefyrka/changelog#1010) or just pass a focus node to ZefyrEditor widget.

**Comment by LoveCTTS** [comment]
> @LoveCTTS Thank you for your feedback! The issue was in a missed focus node. Now Zeryrka doesn't require a focus node. Please update to [1.0.10](https://pub.dev/packages/zefyrka/changelog#1010) or just pass a focus node to ZefyrEditor widget.

Thank you glynskyi^^.
