### ISSUE TITLE
ZefyrToolbar only shows buttons when set to hide

### ISSUE THREAD

**Issue by Marcosmaliki** [glynskyi/zefyrka#3]
Hi @glynskyi, thank you for this Zefyr like package. I've noticed that the Toolbar only shows the buttons when we set them to be hidden, if no parameters are passed then no button is drawn.

Example
`  ZefyrToolbar.basic(
                controller: _controller,
                hideBoldButton: true,
                hideItalicButton: true,
              ),`

This draws the **bold** and _italic_ button

**Comment by glynskyi** [comment]
fixed in [zefyrka: ^1.0.2](https://pub.dev/packages/zefyrka/changelog#102)
