### ISSUE TITLE
Build fail on: The non-abstract class 'RawEditorState' is missing implementations for these members

### ISSUE THREAD

**Issue by FelixYew** [glynskyi/zefyrka#31]
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyrka-1.0.9/lib/src/widgets/editor.dart:722:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
     - TextSelectionDelegate.copySelection
     - TextSelectionDelegate.cutSelection
     - TextSelectionDelegate.pasteText
     - TextSelectionDelegate.selectAll
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class RawEditorState extends EditorState
          ^^^^^^^^^^^^^^
    ../../../../flutter/packages/flutter/lib/src/services/text_input.dart:948:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
      void copySelection(SelectionChangedCause cause) {
           ^^^^^^^^^^^^^
    ../../../../flutter/packages/flutter/lib/src/services/text_input.dart:872:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
      void cutSelection(SelectionChangedCause cause) {
           ^^^^^^^^^^^^
    ../../../../flutter/packages/flutter/lib/src/services/text_input.dart:900:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
      Future<void> pasteText(SelectionChangedCause cause) async {
                   ^^^^^^^^^
    ../../../../flutter/packages/flutter/lib/src/services/text_input.dart:928:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
      void selectAll(SelectionChangedCause cause) {
           ^^^^^^^^^

**Comment by featzima** [comment]
Please try preview version https://pub.dev/packages/zefyrka/versions/1.1.0-dev.1

**Comment by FelixYew** [comment]
Cool that works. Thanks.

**Comment by kaldevops** [comment]
zefyrka is also showing me the same error

**Comment by ajaykrsna** [comment]
$ flutter pub upgrade --major-versions
$ dart fix --apply (Flutter 3.0.1)
