### ISSUE TITLE
Package version 1.1.1 not installing ...

### ISSUE THREAD

**Issue by saguado69** [glynskyi/zefyrka#43]
My pubspec.yaml defines sdk: ">=2.15.0-144.0.dev <3.0.0" but cannot install the package:

Running "flutter pub get" in myapp...                         
The current Dart SDK version is 2.15.0-144.0.dev.

Because myapp depends on zefyrka >=1.1.0 which requires SDK version >=2.15.0 <3.0.0, version solving failed.
pub get failed (1; Because myapp depends on zefyrka >=1.1.0 which requires SDK version >=2.15.0 <3.0.0, version solving failed.)

**Comment by glynskyi** [comment]
@saguado69  Please updated your pubspec file as following:
```yaml
environment:
  sdk: '>=2.15.0 <3.0.0'
```

**Comment by saguado69** [comment]
Thanks for your help @glynskyi, worked fine. Is there any way to change ZefyrEditor backgroung and ZefyrToolbar active button color?
