### ISSUE TITLE
Can't install the zefyrka dependency.

### ISSUE THREAD

**Issue by darkworld000999** [glynskyi/zefyrka#6]
[baatdilki] flutter pub get
Running "flutter pub get" in baatdilki...                       
Because every version of flutter_test from sdk depends on meta 1.3.0 and zefyrka >=1.0.2 depends on meta ^1.4.0, flutter_test from sdk is incompatible with zefyrka >=1.0.2.
So, because baatdilki depends on both zefyrka ^1.0.2+1 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because baatdilki depends on both zefyrka ^1.0.2+1 and flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by antonygunawan94** [comment]
hello, you can try to add

`dependency_overrides: meta: ^1.4.0` into your `pubspec.yaml`

hope it can solve the problem

**Comment by glynskyi** [comment]
fixed in [zefyrka: ^1.0.3](https://pub.dev/packages/zefyrka/changelog#103)
